name: Update Google Spreadsheet with Sensor Data

on:
  push:
    branches:
      - main

jobs:
  update-spreadsheet:
    runs-on: ubuntu-latest

    steps:
      - name: Push Sensor Data to Google Spreadsheet
        env:
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        run: |
          # Replace this command with your cURL command to push data to Google Spreadsheet
          # Example:
          curl -X POST -d '{"sensor_data": m_data}' "$SPREADSHEET_URL"
